### ISSUE TITLE
Python code should create output directory if it doesn't exist

### ISSUE THREAD

**Issue by dowobeha** [tmills/uhhmm#1]
python scripts/d1trainer.py config/d1train.ini
INFO:root:Initializing state
DEBUG:ihmm:Value of amax=6, b_max=6, g_max=11
DEBUG:root:[1, 2, 3, 4, 5, 6, 7, 8]
DEBUG:root:['-/- 0/0:1', '+/- 1/3:4', '-/- 4/2:3', '-/- 4/3:6', '+/+ 4/1:7', '-/- 2/4:9', '-/- 4/5:5', '+/+ 4/3:9']
DEBUG:root:Sampling time for this batch is 765 s
DEBUG:root:Building counts tables took 0 s
DEBUG:root:Resampling models took 0 s
DEBUG:root:Sampling time for this batch is 771 s
DEBUG:root:Building counts tables took 0 s
Traceback (most recent call last):
  File "scripts/d1trainer.py", line 109, in <module>
    main(sys.argv[1:])
  File "scripts/d1trainer.py", line 28, in main
    (samples, stats) = ihmm.sample_beam(word_seq, params, lambda x: write_output(x, None, config))
  File "/home/lanes/uhhmm.git/scripts/ihmm.py", line 208, in sample_beam
    report_function(sample)
  File "scripts/d1trainer.py", line 28, in <lambda>
    (samples, stats) = ihmm.sample_beam(word_seq, params, lambda x: write_output(x, None, config))
  File "scripts/d1trainer.py", line 71, in write_output
    with open(output_dir + "/config.ini", 'w') as configfile:
IOError: [Errno 2] No such file or directory: 'outputs/d1sents/config.ini'
make: **\* [all] Error 1

**Comment by wschuler** [comment]
this can be done by the make item if you add   " | output"  and to Makefile
add item:

output:
[tab] mkdir $@

**Comment by dowobeha** [comment]
William,

I know this can be done by make, but it should be done by the python code.
At the least, the python code should check that the directory exists before
running the trainer.

Lane

On Thu, May 7, 2015 at 8:50 AM, wschuler notifications@github.com wrote:

> this can be done by the make item if you add " | output" and to Makefile
> add item:
> 
> output:
> [tab] mkdir $@
> 
> On Thu, May 7, 2015 at 9:28 AM, Lane Schwartz notifications@github.com
> wrote:
> 
> > python scripts/d1trainer.py config/d1train.ini
> > INFO:root:Initializing state
> > DEBUG:ihmm:Value of amax=6, b_max=6, g_max=11
> > DEBUG:root:[1, 2, 3, 4, 5, 6, 7, 8]
> > DEBUG:root:['-/- 0/0:1', '+/- 1/3:4', '-/- 4/2:3', '-/- 4/3:6', '+/+
> > 4/1:7', '-/- 2/4:9', '-/- 4/5:5', '+/+ 4/3:9']
> > DEBUG:root:Sampling time for this batch is 765 s
> > DEBUG:root:Building counts tables took 0 s
> > DEBUG:root:Resampling models took 0 s
> > DEBUG:root:Sampling time for this batch is 771 s
> > DEBUG:root:Building counts tables took 0 s
> > Traceback (most recent call last):
> > File "scripts/d1trainer.py", line 109, in
> > main(sys.argv[1:])
> > File "scripts/d1trainer.py", line 28, in main
> > (samples, stats) = ihmm.sample_beam(word_seq, params, lambda x:
> > write_output(x, None, config))
> > File "/home/lanes/uhhmm.git/scripts/ihmm.py", line 208, in sample_beam
> > report_function(sample)
> > File "scripts/d1trainer.py", line 28, in
> > (samples, stats) = ihmm.sample_beam(word_seq, params, lambda x:
> > write_output(x, None, config))
> > File "scripts/d1trainer.py", line 71, in write_output
> > with open(output_dir + "/config.ini", 'w') as configfile:
> > IOError: [Errno 2] No such file or directory:
> > 'outputs/d1sents/config.ini'
> > make: **\* [all] Error 1
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/tmills/uhhmm/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tmills/uhhmm/issues/1#issuecomment-99875032.

## 

When a place gets crowded enough to require ID's, social collapse is not
far away.  It is time to go elsewhere.  The best thing about space travel
is that it made it possible to go elsewhere.
                -- R.A. Heinlein, "Time Enough For Love"
