### ISSUE TITLE
tons of pos

### ISSUE THREAD

**Issue by lifengjin** [tmills/uhhmm#44]
I am seeing this for some reason. I am at 1800 iterations with d=2 5/5/10
INFO:root:Have 10043563 pos counts, 10043563 lex counts before sample - should equal number of tokens 7603

WARNING:root:This iteration has 10043563 pos counts for 7603 tokens

**Comment by tmills** [comment]
since the pos and lex counts this looks to me like maybe it's not resetting counts between iterations? I can try to take a quick look sometime today.

**Comment by tmills** [comment]
Was it running in batch mode? I.e. does your output have any of these lines:
INFO:root:Resetting all counts to zero for next iteration

**Comment by lifengjin** [comment]
I lost the output. The model was using just normal config file, so I think the batch mode was not on. But I did stop and start the job for several times. Don't know if that was the issue.

**Comment by tmills** [comment]
Ah, ok I continued a job that worked fine and now see the warning. Seems like it's not resetting if it reloads the models. I'll check in a fix asap.
