### ISSUE TITLE
Bad sample error

### ISSUE THREAD

**Issue by coryshain** [tmills/uhhmm#48]
I had a CPU run going of the current master version and it crashed after a little more than 400 iterations because it sampled a g value of 0. I haven't seen this error before, so it may be newly introduced. I'm starting an otherwise identical run with the GPU in order to see whether the problem replicates there.

**Comment by tmills** [comment]
OK, thanks. I'll keep an eye out for it too.

**Comment by coryshain** [comment]
FYI, I got the same error with the GPU run at iteration 538.

**Comment by coryshain** [comment]
It looks like
