### ISSUE TITLE
p factoring merge

### ISSUE THREAD

**Issue by lifengjin** [tmills/uhhmm#53]
Accidentally merged the p factoring branch into the master. Try not to pull at this time... Sorry about that.

**Comment by tmills** [comment]
What is the timeline on this? Are you going to roll back master or finish the patch?

**Comment by lifengjin** [comment]
I am doing a bit debugging with this, but it is mostly usable. I will finish the batch soon.

**Comment by lifengjin** [comment]
math checked. the patch is pushed.

**Comment by lifengjin** [comment]
The current setup is that when you set gpu=1, the models dumped out will be g-factorized one, and when you set gpu=0, they will be normal old-style models. This means that if you set gpu=1 and num_procs > 1, the CPU workers cannot use the models correctly because they still sample with the full pi matrix. They will be updated when we are confident that the GPU sampler is working correctly (we are almost there).

For now, what you can do is to set gpu=0 and num_procs=whatever to use the old-style sampling with CPU workers, or gpu=1 and num_procs=1 to use the new sampling with GPU workers.

**Comment by tmills** [comment]
So is the factorized model inference only implemented in the gpu/cuda code? With its own model builder I assume?

**Comment by lifengjin** [comment]
Yes to the inference part. The model builder is shared. It can build complete or partial pi according some parameter.

**Comment by tmills** [comment]
Can we close this?
